In [1]:
import numpy as np
from matplotlib import pyplot as plt

plt.style.use('default')
np.random.seed(123)

Below codes are composed with first cell the answer of problem is in and second cell printng out the results of first cell.

# 1

In [2]:
A = np.eye(3)

In [3]:
print(A.shape, A, sep='\n')

(3, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 2

In [108]:
B = np.random.rand(3,3)

In [109]:
print(B.shape, B, sep='\n')

(3, 3)
[[0.25045537 0.48303426 0.98555979]
 [0.51948512 0.61289453 0.12062867]
 [0.8263408  0.60306013 0.54506801]]


# 3

In [110]:
C = np.sqrt(B)

In [7]:
print(C)

[[0.83454729 0.53491993 0.47628925]
 [0.74250574 0.84821517 0.65046634]
 [0.9903354  0.8275444  0.69349254]]


In [8]:
for i in range(len(B)):
    for j in range(len(B)):
        b = np.sqrt(B[i][j])
        a = b**2
        print(B[i][j], f'The sqrt is {b}  {a}',sep = ' ')

0.6964691855978616 The sqrt is 0.8345472938053671  0.6964691855978616
0.28613933495037946 The sqrt is 0.5349199332146629  0.2861393349503794
0.2268514535642031 The sqrt is 0.4762892540927237  0.22685145356420314
0.5513147690828912 The sqrt is 0.742505736733994  0.5513147690828912
0.7194689697855631 The sqrt is 0.8482151671513326  0.7194689697855631
0.42310646012446096 The sqrt is 0.6504663405007679  0.4231064601244609
0.9807641983846155 The sqrt is 0.9903353969159213  0.9807641983846154
0.6848297385848633 The sqrt is 0.8275444027874657  0.6848297385848632
0.48093190148436094 The sqrt is 0.6934925388815376  0.48093190148436094


# 4

In [9]:
D = C@C

In [31]:
print(D)
for k in range(3):

    for j in range(3):
        
        x = 0
        for i in range(3):
            x += C[k][i]*C[i][j]
        print(x)

[[1.56533641 1.29429369 1.07573636]
 [1.89364062 1.65493987 1.35647647]
 [2.1277284  1.80558173 1.49090779]]
1.5653364122018196
1.2942936895633501
1.0757363635534731
1.8936406223212379
1.6549398681738716
1.356476473173637
2.127728400679124
1.8055817272401864
1.4909077882661228


# 5

In [29]:
print(B==D)

[[False False False]
 [False False False]
 [False False False]]


In [50]:
for i in range(3):
    print(f'{B[i][0]:.4} {B[i][1]:.4} {B[i][2]:.4}  {D[i][0]:.4} {D[i][1]:.4} {D[i][2]:.4}')

0.6965 0.2861 0.2269  1.565 1.294 1.076
0.5513 0.7195 0.4231  1.894 1.655 1.356
0.9808 0.6848 0.4809  2.128 1.806 1.491


# 6

In [32]:
F = np.diag(A)

In [33]:
print(F)

[1. 1. 1.]


# 7

In [73]:
print(np.array_equal(A,np.identity(3)))


True


In [52]:
print(A==1)

[[ True False False]
 [False  True False]
 [False False  True]]


# 8

In [81]:
print(B[B>0.5])

[0.69646919 0.55131477 0.71946897 0.9807642  0.68482974]


In [84]:
print(B)
print(B > 0.5)

[[0.69646919 0.28613933 0.22685145]
 [0.55131477 0.71946897 0.42310646]
 [0.9807642  0.68482974 0.4809319 ]]
[[ True False False]
 [ True  True False]
 [ True  True False]]


# 9

In [90]:
B[B < 0.5] = -1*B[B < 0.5] 

In [91]:
print(B)

[[ 0.69646919 -0.28613933 -0.22685145]
 [ 0.55131477  0.71946897 -0.42310646]
 [ 0.9807642   0.68482974 -0.4809319 ]]


# 10

In [98]:
print(np.std(B,ddof=1))

0.5847709245543481


# 11

In [147]:
v = np.arange(100)**2

In [148]:
print(v)
print(v.shape)
type(v)
len(v)

[   0    1    4    9   16   25   36   49   64   81  100  121  144  169
  196  225  256  289  324  361  400  441  484  529  576  625  676  729
  784  841  900  961 1024 1089 1156 1225 1296 1369 1444 1521 1600 1681
 1764 1849 1936 2025 2116 2209 2304 2401 2500 2601 2704 2809 2916 3025
 3136 3249 3364 3481 3600 3721 3844 3969 4096 4225 4356 4489 4624 4761
 4900 5041 5184 5329 5476 5625 5776 5929 6084 6241 6400 6561 6724 6889
 7056 7225 7396 7569 7744 7921 8100 8281 8464 8649 8836 9025 9216 9409
 9604 9801]
(100,)


100

# 12

In [149]:
w = v[1::2].reshape(2,25)

In [151]:
print(w)
print(w.shape)
type(w)
len(w)

[[   1    9   25   49   81  121  169  225  289  361  441  529  625  729
   841  961 1089 1225 1369 1521 1681 1849 2025 2209 2401]
 [2601 2809 3025 3249 3481 3721 3969 4225 4489 4761 5041 5329 5625 5929
  6241 6561 6889 7225 7569 7921 8281 8649 9025 9409 9801]]
(2, 25)


2

# 13

In [154]:
print(np.median(w,axis = 1))

[ 625. 5625.]


# 14

In [161]:
print('the flux ratio of each difference is',10**np.arange(5))

the flux ratio of each difference is [    1    10   100  1000 10000]


# 15

In [206]:
np.log10(np.arange(0.1,2.1,0.10))

array([-1.        , -0.69897   , -0.52287875, -0.39794001, -0.30103   ,
       -0.22184875, -0.15490196, -0.09691001, -0.04575749,  0.        ,
        0.04139269,  0.07918125,  0.11394335,  0.14612804,  0.17609126,
        0.20411998,  0.23044892,  0.25527251,  0.2787536 ,  0.30103   ])